-- SafeTrackKids Database Schema (from ERD)
-- Run this in Supabase Dashboard → SQL Editor to create all tables.

-- 1. USER table (quoted because USER is a reserved word in SQL)
CREATE TABLE IF NOT EXISTS "USER" (
  "User_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Username" text,
  "Password" text,
  "Role" text,
  "Email" text UNIQUE NOT NULL
);

-- 2. ORGANIZER table
CREATE TABLE IF NOT EXISTS "ORGANIZER" (
  "Organizer_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Contact_Email" text,
  "Organization_Name" text,
  "User_ID" bigint NOT NULL REFERENCES "USER"("User_ID") ON DELETE CASCADE
);

-- 3. EVENT table
CREATE TABLE IF NOT EXISTS "EVENT" (
  "Event_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Event_Name" text,
  "Location_Name" text,
  "Geofence_Coordinates" text,
  "Start_Time" timestamptz,
  "End_Time" timestamptz,
  "Status" text,
  "Organizer_ID" bigint NOT NULL REFERENCES "ORGANIZER"("Organizer_ID") ON DELETE CASCADE
);

-- 4. BRACELET table
CREATE TABLE IF NOT EXISTS "BRACELET" (
  "Bracelet_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MAC_Address" text,
  "QR_Code_String" text,
  "Status" text,
  "Battery_Level" integer
);

-- 5. PARENT table
CREATE TABLE IF NOT EXISTS "PARENT" (
  "Parent_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" text,
  "Phone_Number" text,
  "Device_Token" text,
  "User_ID" bigint NOT NULL REFERENCES "USER"("User_ID") ON DELETE CASCADE
);

-- 6. CHILD table
CREATE TABLE IF NOT EXISTS "CHILD" (
  "Child_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" text,
  "Age" integer,
  "Medical_Notes" text,
  "Parent_ID" bigint NOT NULL REFERENCES "PARENT"("Parent_ID") ON DELETE CASCADE
);

-- 7. Active_Sessions table
CREATE TABLE IF NOT EXISTS "Active_Sessions" (
  "Session_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Check_In_Time" timestamptz,
  "Is_Active" boolean DEFAULT true,
  "Check_Out_Time" timestamptz,
  "Child_ID" bigint NOT NULL REFERENCES "CHILD"("Child_ID") ON DELETE CASCADE,
  "Bracelet_ID" bigint NOT NULL REFERENCES "BRACELET"("Bracelet_ID") ON DELETE CASCADE,
  "Event_ID" bigint NOT NULL REFERENCES "EVENT"("Event_ID") ON DELETE CASCADE
);

-- 8. Location_Logs table
CREATE TABLE IF NOT EXISTS "Location_Logs" (
  "Log_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Is_Out_Of_Zone" boolean DEFAULT false,
  "Timestamp" timestamptz DEFAULT now(),
  "Longitude" double precision,
  "Latitude" double precision,
  "Session_ID" bigint NOT NULL REFERENCES "Active_Sessions"("Session_ID") ON DELETE CASCADE
);

-- Optional: Enable Row Level Security (RLS) and add policies as needed for your app.
-- ALTER TABLE "USER" ENABLE ROW LEVEL SECURITY;
-- (Repeat for other tables and add policies in Supabase Dashboard.)
